In [1]:
from mxnet import autograd, nd
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = nd.random.normal(scale=1, shape=(num_examples, num_inputs))
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += nd.random.normal(scale=0.01, shape=labels.shape)

In [2]:
from mxnet.gluon import data as gdata

batch_size = 10
dataset = gdata.ArrayDataset(features, labels)
data_iter = gdata.DataLoader(dataset, batch_size, shuffle=True)

In [3]:
for X, y in data_iter:
    print(X, y)
    break

(
[[-1.4270164e+00  1.9242623e-01]
 [-7.4377191e-01  5.6905705e-01]
 [-1.0512875e+00 -3.0882603e-01]
 [-4.1334660e-04  1.3946280e+00]
 [ 1.7922944e-01 -6.4657003e-02]
 [-2.0099306e+00  1.2595973e+00]
 [ 1.3671521e+00  4.3007031e-01]
 [-1.8462065e-01 -1.4264767e+00]
 [-3.7749559e-01 -1.6566036e+00]
 [ 4.4809967e-01  6.2437933e-03]]
<NDArray 10x2 @cpu(0)>, 
[ 0.6849268  0.7757994  3.1587188 -0.5529463  4.785132  -4.1031957
  5.4759536  8.690022   9.081717   5.088348 ]
<NDArray 10 @cpu(0)>)


In [4]:
from mxnet.gluon import nn
net = nn.Sequential()

In [5]:
net.add(nn.Dense(1))

In [6]:
from mxnet import init
net.initialize(init.Normal(sigma=0.01))

In [11]:
from mxnet.gluon import loss as gloss
loss = gloss.L2Loss()

In [12]:
from mxnet import gluon
trainer = gluon.Trainer(net.collect_params(), "sgd", {"learning_rate": 0.03})

In [13]:
num_epochs=3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        with autograd.record():
            l = loss(net(X), y)
        l.backward()
        trainer.step(batch_size)
    l = loss(net(features), labels)
    print("epoch %d, loss:%f" % (epoch, l.mean().asnumpy()))

epoch 1, loss:0.040708
epoch 2, loss:0.000151
epoch 3, loss:0.000050


In [14]:
dense = net[0]
true_w, dense.weight.data()

([2, -3.4], 
 [[ 1.9993957 -3.3996537]]
 <NDArray 1x2 @cpu(0)>)

In [15]:
true_b, dense.bias.data()

(4.2, 
 [4.2002354]
 <NDArray 1 @cpu(0)>)

In [17]:
print(dense.weight.data())


[[ 1.9993957 -3.3996537]]
<NDArray 1x2 @cpu(0)>
