In [10]:
%matplotlib inline
import d2lzh as d2l
from mxnet import autograd, nd

In [12]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size) 

In [15]:
num_inputs = 784
num_outputs = 10

W = nd.random.normal(scale=0.01, shape=(num_inputs, num_outputs))
b = nd.zeros(num_outputs)

In [16]:
W.attach_grad()
b.attach_grad()

In [19]:
X = nd.array([[1,2,3],[4,5,6]])
X.sum(axis=0, keepdims=True), X.sum(axis=1, keepdims=True)

(
 [[5. 7. 9.]]
 <NDArray 1x3 @cpu(0)>, 
 [[ 6.]
  [15.]]
 <NDArray 2x1 @cpu(0)>)

In [26]:
def softmax(X):
    X_exp = X.exp()
    partition = X_exp.sum(axis=1, keepdims=True)
    return X_exp / partition

In [27]:
X = nd.random.normal(shape=(2,5))
X_prob = softmax(X)
X_prob, X_prob.sum(axis=1)

(
 [[0.40908694 0.06355722 0.1251719  0.13770238 0.26448157]
  [0.12531236 0.28633645 0.3586819  0.1256007  0.10406859]]
 <NDArray 2x5 @cpu(0)>, 
 [1. 1.]
 <NDArray 2 @cpu(0)>)

In [28]:
def net(X):
    return softmax(nd.dot(X.reshape((-1, num_inputs)), W)+b)

In [29]:
y_hat = nd.array([[0.1, 0.3, 0.6],[0.3, 0.2, 0.5]])
y = nd.array([0, 2], dtype="int32")
nd.pick(y_hat, y)


[0.1 0.5]
<NDArray 2 @cpu(0)>

In [ ]:
def cross_entropy(y_hat, y):
    return -nd.pick(y_hat, y).log()