In [12]:
%matplotlib inline
import d2lzh as d2l
from mxnet import autograd, nd

In [13]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size) 

In [14]:
num_inputs = 784
num_outputs = 10

W = nd.random.normal(scale=0.01, shape=(num_inputs, num_outputs))
b = nd.zeros(num_outputs)

In [15]:
W.attach_grad()
b.attach_grad()

In [16]:
X = nd.array([[1,2,3],[4,5,6]])
X.sum(axis=0, keepdims=True), X.sum(axis=1, keepdims=True) # 是哪个轴就按照哪个轴相加

(
 [[5. 7. 9.]]
 <NDArray 1x3 @cpu(0)>, 
 [[ 6.]
  [15.]]
 <NDArray 2x1 @cpu(0)>)

In [17]:
def softmax(X):
    X_exp = X.exp()
    partition = X_exp.sum(axis=1, keepdims=True) #  横轴相加
    return X_exp / partition

In [18]:
X = nd.random.normal(shape=(2,5))
X_prob = softmax(X)
X_prob, X_prob.sum(axis=1)

(
 [[0.24463879 0.1821904  0.32824865 0.15328218 0.09163998]
  [0.29803687 0.04758069 0.25445914 0.16223735 0.237686  ]]
 <NDArray 2x5 @cpu(0)>, 
 [1. 1.]
 <NDArray 2 @cpu(0)>)

In [19]:
def net(X):
    return softmax(nd.dot(X.reshape((-1, num_inputs)), W)+b)

In [20]:
y_hat = nd.array([[0.1, 0.3, 0.6],[0.3, 0.2, 0.5]])
y = nd.array([0, 2], dtype="int32")
nd.pick(y_hat, y)


[0.1 0.5]
<NDArray 2 @cpu(0)>

In [21]:
def cross_entropy(y_hat, y):
    return -nd.pick(y_hat, y).log()

In [22]:
def accuracy(y_hat, y):
    return (y_hat.argmax(axis=1) == y.astype("float32")).mean().asscalar()

In [23]:
accuracy(y_hat, y)

0.5

In [24]:
def evaluate_accuracy(data_iter, net):
    acc_sum, n = 0.0, 0
    for X, y in data_iter:
        y = y.astype("float32")
        acc_sum += (net(X).argmax(axis=1) == y).sum().asscalar()
        n += y.size
    return acc_sum / n

In [25]:
evaluate_accuracy(test_iter, net)

0.1125

In [27]:
num_epochs, lr = 5, 0.1
def train_ch3(net, train_iter, test_iter, loss, num_epochs,
              batch_size, params=None, lr=None, trainer=None):

SyntaxError: invalid syntax (<ipython-input-27-c3f6cf31bf96>, line 1)