In [1]:
%matplotlib inline
import d2lzh as d2l
from mxnet import autograd, nd

In [2]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size) 

In [3]:
num_inputs = 784
num_outputs = 10

W = nd.random.normal(scale=0.01, shape=(num_inputs, num_outputs))
b = nd.zeros(num_outputs)

In [4]:
W.attach_grad()
b.attach_grad()

In [5]:
X = nd.array([[1,2,3],[4,5,6]])
X.sum(axis=0, keepdims=True), X.sum(axis=1, keepdims=True) # 是哪个轴就按照哪个轴相加

(
 [[5. 7. 9.]]
 <NDArray 1x3 @cpu(0)>, 
 [[ 6.]
  [15.]]
 <NDArray 2x1 @cpu(0)>)

In [6]:
def softmax(X):
    X_exp = X.exp()
    partition = X_exp.sum(axis=1, keepdims=True) #  横轴相加
    return X_exp / partition

In [7]:
X = nd.random.normal(shape=(2,5))
X_prob = softmax(X)
X_prob, X_prob.sum(axis=1)

(
 [[0.21324193 0.33961776 0.1239742  0.27106097 0.05210521]
  [0.11462264 0.3461234  0.19401033 0.29583326 0.04941036]]
 <NDArray 2x5 @cpu(0)>, 
 [1.0000001 1.       ]
 <NDArray 2 @cpu(0)>)

In [8]:
def net(X):
    return softmax(nd.dot(X.reshape((-1, num_inputs)), W)+b)

In [9]:
y_hat = nd.array([[0.1, 0.3, 0.6],[0.3, 0.2, 0.5]])
y = nd.array([0, 2], dtype="int32")
nd.pick(y_hat, y)


[0.1 0.5]
<NDArray 2 @cpu(0)>

In [10]:
def cross_entropy(y_hat, y):
    return -nd.pick(y_hat, y).log()